hw_17/flask_app/app/models/base.py
import sqlalchemy as sa
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    first_name = sa.Column(sa.String(50), nullable=False)
    last_name = sa.Column(sa.String(50), nullable=False)
    email = sa.Column(sa.String(100), nullable=False, unique=True)
    user_name = sa.Column(sa.String(50), nullable=False, unique=True)
    password = sa.Column(sa.String(256), nullable=False)


class TestingMigrations(db.Model):
    __tablename__ = "test_users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))

hw_17/flask_app/app/main.py
import os

from app.models.base import db
from app.users.api.methods import LoginUser, SingleUser, UserRegister, UsersList
from app.users.api.sequre_check import login_manager
from app.views.auth import auth
from app.views.main import main
from flask import Flask
from flask_marshmallow import Marshmallow
from flask_migrate import Migrate
from flask_restful import Api
from flask_sqlalchemy import SQLAlchemy


def create_app() -> Flask:
    app = Flask(__name__)
    api = Api(app)

    Migrate(app, db)

    app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://d.ulasovets:lastochka1488@localhost:5432/flask_test"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
    app.config["SECRET_KEY"] = "3d6f45a5fc12445dbac2f59c3b6c7cb1"

    db.init_app(app)
    db.create_all(app=app)

    login_manager.init_app(app)

    api.add_resource(UsersList, "/api/users")
    api.add_resource(SingleUser, "/api/users/<int:pk>")
    api.add_resource(UserRegister, "/api/user-register")
    api.add_resource(LoginUser, "/api/user-login")

    app.register_blueprint(main)
    app.register_blueprint(auth)

    return app

hw_17/flask_app/app/views/auth.py
import flask
from flask_login import login_required, login_user, logout_user

auth = flask.Blueprint("auth", __name__, url_prefix="/")


@auth.route("login", methods=["GET"])
def login():
    return flask.render_template("login.html")


@auth.route("signup", methods=["GET"])
def signup():
    return flask.render_template("signup.html")


@auth.route("logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return flask.render_template("index.html")

hw_17/flask_app/app/views/main.py
import flask
from flask_login import current_user, login_required

main = flask.Blueprint("main", __name__, url_prefix="/")


@main.route("/", methods=["GET"])
def index():
    return flask.render_template("index.html")


@main.route("/profile", methods=["GET"])
@login_required
def profile():
    return flask.render_template("profile.html", name=current_user.user_name)

hw_17/flask_app/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

hw_17/flask_app/app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

hw_17/flask_app/app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/api/user-login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="user_name" placeholder="Your Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

hw_17/flask_app/app/templates/old_temp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% include 'navbar.html' %}

    {% block content%}

        <h1>HW 17</h1>

    {% endblock content %}


</body>
</html>

hw_17/flask_app/app/templates/old_temp/navbar.html
<h1>Navbar</h1>
<a href="{{ url_for('get_register_page') }}">Registration</a>
<hr>

hw_17/flask_app/app/templates/old_temp/registration.html
<Html>
    <head>
        <title>
            Registration Page
        </title>
    </head>

        <body bgcolor="Lightskyblue">
            <br>
            <h1>Registration</h1>
            <br>
            <form action="http://localhost:5000/api/users" method="POST">
                <label> Firstname </label>
                <input type="text" name="first_name" size="15"/> <br> <br>
                <label> Lastname: </label>
                <input type="text" name="last_name" size="15"/> <br> <br>
                <label> Username: </label>
                <input type="text" name="user_name" size="15"/> <br> <br>
                <label> Email: </label>
                <input type="email" id="email" name="email"/> <br> <br>
                <label>Password: </label>
                <input type="Password" id="password" name="password"> <br>
                <br> <br>
                <input type="submit" value="Register">
            </form>
    </body>
</html>

hw_17/flask_app/app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}
</h1>
{% endblock %}

hw_17/flask_app/app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/api/user-register">

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="first_name" placeholder="First name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="last_name" placeholder="Last name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="user_name" placeholder="Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}